name: CI

on:
  push:
    branches:
    - action
    tags:
    - '*'

jobs:
  build_and_release:
    name: chisel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go 1.23.4
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Build for linux x86_64
        run: |
          make linux-x86_64

      - name: Build for linux aarch64
        run: |
          make linux-aarch64

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/chisel*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
